### ISSUE TITLE
Weather/General Weather Data Point Appears as "undefined"

### ISSUE THREAD

**Issue by dvo-orlando** [dvo-orlando/snowday#2]
The geolookup .json clearly outputs the current weather as "partly cloudy" or "overcast" etc.  When printed to the page, appears as "undefined."

**Comment by vorlando** [comment]
The `var` assignment for `general_weather` is not complete. 
You need to include the associative array `parsed_json` in the assignment.

Also consider the dot notation for associative arrays. You can change
`parsed_json['current_observation']['weather']` to
`parsed_json.current_observation.weather`. It is easier to read.

See my pull request #3
